version: '3'

services:
#  migrations:
#    network_mode: host
#    build: ./db

  redis:
    network_mode: host
    image: redis:3.2-alpine
    expose:
      - 6379
    restart: always

#  cron:
#    build: .
#    depends_on:
#      - redis
#      - migrations
#    env_file:
#      - .env-cron
#    restart: always

  nats:
    network_mode: host
    image: nats:latest
    expose:
      - 4222
    restart: always

#  chats:
#    network_mode: host
#    build: .
#    depends_on:
#      - redis
#      - nats
#      - migrations
#    env_file:
#      - .env
#    ports:
#      - 8086-8087:8000
#    restart: always
