// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: roomService.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SubscriberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *AccountIdRequest `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Role    string            `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *SubscriberRequest) Reset() {
	*x = SubscriberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberRequest) ProtoMessage() {}

func (x *SubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberRequest.ProtoReflect.Descriptor instead.
func (*SubscriberRequest) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriberRequest) GetAccount() *AccountIdRequest {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *SubscriberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *UUID  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Hash string `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{1}
}

func (x *RoomResponse) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RoomResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReferenceId string               `protobuf:"bytes,1,opt,name=ReferenceId,proto3" json:"ReferenceId,omitempty"`
	Chat        bool                 `protobuf:"varint,2,opt,name=Chat,proto3" json:"Chat,omitempty"`
	Video       bool                 `protobuf:"varint,3,opt,name=Video,proto3" json:"Video,omitempty"`
	Audio       bool                 `protobuf:"varint,4,opt,name=Audio,proto3" json:"Audio,omitempty"`
	Subscribers []*SubscriberRequest `protobuf:"bytes,5,rep,name=Subscribers,proto3" json:"Subscribers,omitempty"`
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreateRoomRequest) GetChat() bool {
	if x != nil {
		return x.Chat
	}
	return false
}

func (x *CreateRoomRequest) GetVideo() bool {
	if x != nil {
		return x.Video
	}
	return false
}

func (x *CreateRoomRequest) GetAudio() bool {
	if x != nil {
		return x.Audio
	}
	return false
}

func (x *CreateRoomRequest) GetSubscribers() []*SubscriberRequest {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *RoomResponse `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Errors []*Error      `protobuf:"bytes,2,rep,name=Errors,proto3" json:"Errors,omitempty"`
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetResult() *RoomResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateRoomResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetSubscriberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *UUID      `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AccountId     *UUID      `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Role          string     `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	UnSubscribeAt *Timestamp `protobuf:"bytes,4,opt,name=UnSubscribeAt,proto3" json:"UnSubscribeAt,omitempty"`
}

func (x *GetSubscriberResponse) Reset() {
	*x = GetSubscriberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscriberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriberResponse) ProtoMessage() {}

func (x *GetSubscriberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriberResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriberResponse) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriberResponse) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetSubscriberResponse) GetAccountId() *UUID {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *GetSubscriberResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetSubscriberResponse) GetUnSubscribeAt() *Timestamp {
	if x != nil {
		return x.UnSubscribeAt
	}
	return nil
}

type GetRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *UUID                    `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Hash        string                   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	ReferenceId string                   `protobuf:"bytes,3,opt,name=ReferenceId,proto3" json:"ReferenceId,omitempty"`
	Chat        bool                     `protobuf:"varint,4,opt,name=Chat,proto3" json:"Chat,omitempty"`
	Video       bool                     `protobuf:"varint,5,opt,name=Video,proto3" json:"Video,omitempty"`
	Audio       bool                     `protobuf:"varint,6,opt,name=Audio,proto3" json:"Audio,omitempty"`
	ClosedAt    *Timestamp               `protobuf:"bytes,7,opt,name=ClosedAt,proto3" json:"ClosedAt,omitempty"`
	Subscribers []*GetSubscriberResponse `protobuf:"bytes,8,rep,name=Subscribers,proto3" json:"Subscribers,omitempty"`
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomResponse) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetRoomResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetRoomResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *GetRoomResponse) GetChat() bool {
	if x != nil {
		return x.Chat
	}
	return false
}

func (x *GetRoomResponse) GetVideo() bool {
	if x != nil {
		return x.Video
	}
	return false
}

func (x *GetRoomResponse) GetAudio() bool {
	if x != nil {
		return x.Audio
	}
	return false
}

func (x *GetRoomResponse) GetClosedAt() *Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *GetRoomResponse) GetSubscribers() []*GetSubscriberResponse {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

type GetRoomsByCriteriaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReferenceId     string            `protobuf:"bytes,1,opt,name=ReferenceId,proto3" json:"ReferenceId,omitempty"`
	AccountId       *AccountIdRequest `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	RoomId          *UUID             `protobuf:"bytes,3,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	WithClosed      bool              `protobuf:"varint,4,opt,name=WithClosed,proto3" json:"WithClosed,omitempty"`
	WithSubscribers bool              `protobuf:"varint,5,opt,name=WithSubscribers,proto3" json:"WithSubscribers,omitempty"`
}

func (x *GetRoomsByCriteriaRequest) Reset() {
	*x = GetRoomsByCriteriaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsByCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsByCriteriaRequest) ProtoMessage() {}

func (x *GetRoomsByCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsByCriteriaRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsByCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoomsByCriteriaRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *GetRoomsByCriteriaRequest) GetAccountId() *AccountIdRequest {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *GetRoomsByCriteriaRequest) GetRoomId() *UUID {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *GetRoomsByCriteriaRequest) GetWithClosed() bool {
	if x != nil {
		return x.WithClosed
	}
	return false
}

func (x *GetRoomsByCriteriaRequest) GetWithSubscribers() bool {
	if x != nil {
		return x.WithSubscribers
	}
	return false
}

type GetRoomsByCriteriaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms  []*GetRoomResponse `protobuf:"bytes,1,rep,name=Rooms,proto3" json:"Rooms,omitempty"`
	Errors []*Error           `protobuf:"bytes,2,rep,name=Errors,proto3" json:"Errors,omitempty"`
}

func (x *GetRoomsByCriteriaResponse) Reset() {
	*x = GetRoomsByCriteriaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsByCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsByCriteriaResponse) ProtoMessage() {}

func (x *GetRoomsByCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsByCriteriaResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsByCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomsByCriteriaResponse) GetRooms() []*GetRoomResponse {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRoomsByCriteriaResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type RoomSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId      *UUID                `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	ReferenceId string               `protobuf:"bytes,2,opt,name=ReferenceId,proto3" json:"ReferenceId,omitempty"`
	Subscribers []*SubscriberRequest `protobuf:"bytes,3,rep,name=Subscribers,proto3" json:"Subscribers,omitempty"`
}

func (x *RoomSubscribeRequest) Reset() {
	*x = RoomSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSubscribeRequest) ProtoMessage() {}

func (x *RoomSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSubscribeRequest.ProtoReflect.Descriptor instead.
func (*RoomSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{8}
}

func (x *RoomSubscribeRequest) GetRoomId() *UUID {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *RoomSubscribeRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *RoomSubscribeRequest) GetSubscribers() []*SubscriberRequest {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

type RoomSubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms  []*GetRoomResponse `protobuf:"bytes,1,rep,name=Rooms,proto3" json:"Rooms,omitempty"`
	Errors []*Error           `protobuf:"bytes,2,rep,name=Errors,proto3" json:"Errors,omitempty"`
}

func (x *RoomSubscribeResponse) Reset() {
	*x = RoomSubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSubscribeResponse) ProtoMessage() {}

func (x *RoomSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSubscribeResponse.ProtoReflect.Descriptor instead.
func (*RoomSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{9}
}

func (x *RoomSubscribeResponse) GetRooms() []*GetRoomResponse {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *RoomSubscribeResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CloseRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId      *UUID  `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	ReferenceId string `protobuf:"bytes,2,opt,name=ReferenceId,proto3" json:"ReferenceId,omitempty"`
}

func (x *CloseRoomRequest) Reset() {
	*x = CloseRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomRequest) ProtoMessage() {}

func (x *CloseRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomRequest.ProtoReflect.Descriptor instead.
func (*CloseRoomRequest) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{10}
}

func (x *CloseRoomRequest) GetRoomId() *UUID {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *CloseRoomRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type CloseRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*Error `protobuf:"bytes,1,rep,name=Errors,proto3" json:"Errors,omitempty"`
}

func (x *CloseRoomResponse) Reset() {
	*x = CloseRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomService_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomResponse) ProtoMessage() {}

func (x *CloseRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomService_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomResponse.ProtoReflect.Descriptor instead.
func (*CloseRoomResponse) Descriptor() ([]byte, []int) {
	return file_roomService_proto_rawDescGZIP(), []int{11}
}

func (x *CloseRoomResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_roomService_proto protoreflect.FileDescriptor

var file_roomService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x22, 0x3f, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0xb1, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x43, 0x68, 0x61,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x3a, 0x0a,
	0x0b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x22, 0x67, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x06,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x22, 0xab, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x09, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x55, 0x6e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0d, 0x55, 0x6e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x74,
	0x22, 0x92, 0x02, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x2c, 0x0a, 0x08, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3e, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x73, 0x22, 0xe3, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x73, 0x42, 0x79, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x64, 0x12, 0x28, 0x0a, 0x0f, 0x57, 0x69, 0x74, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x57, 0x69, 0x74, 0x68,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x22, 0x70, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x42, 0x79, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x52, 0x6f, 0x6f,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x05, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x99, 0x01,
	0x0a, 0x14, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x55, 0x49, 0x44, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x3a, 0x0a,
	0x0b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x73, 0x22, 0x6b, 0x0a, 0x15, 0x52, 0x6f, 0x6f,
	0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x52, 0x6f, 0x6f, 0x6d, 0x73,
	0x12, 0x24, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x59, 0x0a, 0x10, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x22, 0x39, 0x0a, 0x11, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x32, 0xab, 0x02, 0x0a,
	0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x3f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x56, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x79, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x73, 0x42, 0x79, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x73, 0x42, 0x79, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x63, 0x68,
	0x61, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_roomService_proto_rawDescOnce sync.Once
	file_roomService_proto_rawDescData = file_roomService_proto_rawDesc
)

func file_roomService_proto_rawDescGZIP() []byte {
	file_roomService_proto_rawDescOnce.Do(func() {
		file_roomService_proto_rawDescData = protoimpl.X.CompressGZIP(file_roomService_proto_rawDescData)
	})
	return file_roomService_proto_rawDescData
}

var file_roomService_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_roomService_proto_goTypes = []interface{}{
	(*SubscriberRequest)(nil),          // 0: proto.SubscriberRequest
	(*RoomResponse)(nil),               // 1: proto.RoomResponse
	(*CreateRoomRequest)(nil),          // 2: proto.CreateRoomRequest
	(*CreateRoomResponse)(nil),         // 3: proto.CreateRoomResponse
	(*GetSubscriberResponse)(nil),      // 4: proto.GetSubscriberResponse
	(*GetRoomResponse)(nil),            // 5: proto.GetRoomResponse
	(*GetRoomsByCriteriaRequest)(nil),  // 6: proto.GetRoomsByCriteriaRequest
	(*GetRoomsByCriteriaResponse)(nil), // 7: proto.GetRoomsByCriteriaResponse
	(*RoomSubscribeRequest)(nil),       // 8: proto.RoomSubscribeRequest
	(*RoomSubscribeResponse)(nil),      // 9: proto.RoomSubscribeResponse
	(*CloseRoomRequest)(nil),           // 10: proto.CloseRoomRequest
	(*CloseRoomResponse)(nil),          // 11: proto.CloseRoomResponse
	(*AccountIdRequest)(nil),           // 12: proto.AccountIdRequest
	(*UUID)(nil),                       // 13: proto.UUID
	(*Error)(nil),                      // 14: proto.Error
	(*Timestamp)(nil),                  // 15: proto.Timestamp
}
var file_roomService_proto_depIdxs = []int32{
	12, // 0: proto.SubscriberRequest.Account:type_name -> proto.AccountIdRequest
	13, // 1: proto.RoomResponse.Id:type_name -> proto.UUID
	0,  // 2: proto.CreateRoomRequest.Subscribers:type_name -> proto.SubscriberRequest
	1,  // 3: proto.CreateRoomResponse.Result:type_name -> proto.RoomResponse
	14, // 4: proto.CreateRoomResponse.Errors:type_name -> proto.Error
	13, // 5: proto.GetSubscriberResponse.Id:type_name -> proto.UUID
	13, // 6: proto.GetSubscriberResponse.AccountId:type_name -> proto.UUID
	15, // 7: proto.GetSubscriberResponse.UnSubscribeAt:type_name -> proto.Timestamp
	13, // 8: proto.GetRoomResponse.Id:type_name -> proto.UUID
	15, // 9: proto.GetRoomResponse.ClosedAt:type_name -> proto.Timestamp
	4,  // 10: proto.GetRoomResponse.Subscribers:type_name -> proto.GetSubscriberResponse
	12, // 11: proto.GetRoomsByCriteriaRequest.AccountId:type_name -> proto.AccountIdRequest
	13, // 12: proto.GetRoomsByCriteriaRequest.RoomId:type_name -> proto.UUID
	5,  // 13: proto.GetRoomsByCriteriaResponse.Rooms:type_name -> proto.GetRoomResponse
	14, // 14: proto.GetRoomsByCriteriaResponse.Errors:type_name -> proto.Error
	13, // 15: proto.RoomSubscribeRequest.RoomId:type_name -> proto.UUID
	0,  // 16: proto.RoomSubscribeRequest.Subscribers:type_name -> proto.SubscriberRequest
	5,  // 17: proto.RoomSubscribeResponse.Rooms:type_name -> proto.GetRoomResponse
	14, // 18: proto.RoomSubscribeResponse.Errors:type_name -> proto.Error
	13, // 19: proto.CloseRoomRequest.RoomId:type_name -> proto.UUID
	14, // 20: proto.CloseRoomResponse.Errors:type_name -> proto.Error
	2,  // 21: proto.GetRoom.Create:input_type -> proto.CreateRoomRequest
	8,  // 22: proto.GetRoom.Subscribe:input_type -> proto.RoomSubscribeRequest
	6,  // 23: proto.GetRoom.GetByCriteria:input_type -> proto.GetRoomsByCriteriaRequest
	10, // 24: proto.GetRoom.CloseRoom:input_type -> proto.CloseRoomRequest
	3,  // 25: proto.GetRoom.Create:output_type -> proto.CreateRoomResponse
	9,  // 26: proto.GetRoom.Subscribe:output_type -> proto.RoomSubscribeResponse
	7,  // 27: proto.GetRoom.GetByCriteria:output_type -> proto.GetRoomsByCriteriaResponse
	11, // 28: proto.GetRoom.CloseRoom:output_type -> proto.CloseRoomResponse
	25, // [25:29] is the sub-list for method output_type
	21, // [21:25] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_roomService_proto_init() }
func file_roomService_proto_init() {
	if File_roomService_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_roomService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscriberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomsByCriteriaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomsByCriteriaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomService_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roomService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roomService_proto_goTypes,
		DependencyIndexes: file_roomService_proto_depIdxs,
		MessageInfos:      file_roomService_proto_msgTypes,
	}.Build()
	File_roomService_proto = out.File
	file_roomService_proto_rawDesc = nil
	file_roomService_proto_goTypes = nil
	file_roomService_proto_depIdxs = nil
}
